<a href="https://colab.research.google.com/github/Callum-pb/sudoku/blob/master/sudoku_solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sudoku Solver
Basic sudoku solver using backtracking algorithm. Will eventually be used as the backend for a playable game, and potentially paired with an image recognition app to solve physically printed Sudoku puzzles.

In [ ]:
import numpy as np

In [ ]:
grid = [[0,2,0,0,0,4,3,0,0],
        [9,0,0,0,2,0,0,0,8],
        [0,0,0,6,0,9,0,5,0],
        [0,0,0,0,0,0,0,0,1],
        [0,7,2,5,0,3,6,8,0],
        [6,0,0,0,0,0,0,0,0],
        [0,8,0,2,0,5,0,0,0],
        [1,0,0,0,9,0,0,0,3],
        [0,0,9,8,0,0,0,6,0]]

In [ ]:
print(np.matrix(grid))

[[0 2 0 0 0 4 3 0 0]
 [9 0 0 0 2 0 0 0 8]
 [0 0 0 6 0 9 0 5 0]
 [0 0 0 0 0 0 0 0 1]
 [0 7 2 5 0 3 6 8 0]
 [6 0 0 0 0 0 0 0 0]
 [0 8 0 2 0 5 0 0 0]
 [1 0 0 0 9 0 0 0 3]
 [0 0 9 8 0 0 0 6 0]]


In [ ]:
#Check input is a valid
def valid(gr,r,c,n):
  #Check row
  for i in range(9):
    if gr[r][i] == n:
      return False
  #Check column
  for i in range(9):
    if gr[i][c] == n:
      return False
  #Check 3x3 square
  x0 = 3 * (c//3)
  y0 = 3 * (r//3)
  for i in range(3):
    for j in range(3):
      if grid[y0+i][x0+j] == n:
        return False
  return True

In [ ]:
#Solve grid passed in
def solve(gr):
  for y in range(9):
    for x in range(9):
      if gr[y][x] == 0:
        for n in range(1,10):
          if valid(gr,y,x,n):
            gr[y][x] = n
            solve(gr)
            grid[y][x] = 0
        return
  print(np.matrix(gr))   

In [ ]:
solve(grid)

[[8 2 7 1 5 4 3 9 6]
 [9 6 5 3 2 7 1 4 8]
 [3 4 1 6 8 9 7 5 2]
 [5 9 3 4 6 8 2 7 1]
 [4 7 2 5 1 3 6 8 9]
 [6 1 8 9 7 2 4 3 5]
 [7 8 6 2 3 5 9 1 4]
 [1 5 4 7 9 6 8 2 3]
 [2 3 9 8 4 1 5 6 7]]


# Image Processing
Import image of sudoku grid. Parse it to 2D array for later.

In [ ]:
!sudo apt install tesseract-ocr
!pip install pytesseract

In [ ]:
import cv2 as cv
from google.colab.patches import cv2_imshow # for image display
import pytesseract # OCR
from skimage import io #reading from url

In [ ]:
img = cv.imread('sudoku_unsolved.jpg')
img = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
cv2_imshow(img)

In [ ]:
th_b = cv.threshold(img,127,255,cv.THRESH_BINARY)

In [ ]:
cv2_imshow(th_b)

AttributeError: ignored